# File: .github/workflows/scrape-chunked.yml
name: Chunked RKGuns Scrape

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        range:
          - "1-20"
          - "21-40"
          - "41-60"
          - "61-80"
          - "81-100"
          - "101-120"
          - "121-140"
          - "141-160"
          - "161-180"
          - "181-200"
          - "201-220"
          - "221-240"
          - "241-260"
          - "261-278"

    env:
      PAGES: ${{ matrix.range }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse START/END
        run: |
          IFS="-" read START END <<< "${PAGES}"
          echo "START_PAGE=$START" >> $GITHUB_ENV
          echo "END_PAGE=$END"   >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip selenium chromedriver-autoinstaller

      - name: Run chunked scraper
        run: python scraper_selenium_chunked.py

      - name: Upload chunk CSV
        uses: actions/upload-artifact@v4
        with:
          name: inventory_${{ env.START_PAGE }}_${{ env.END_PAGE }}.csv
          path: inventory_${{ env.START_PAGE }}_${{ env.END_PAGE }}.csv

  merge:
    needs: scrape
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download all chunk CSVs
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Merge into inventory.csv
        run: |
          # Find header from the first chunk
          first=$(find . -type f -name 'inventory_1_20.csv' | head -n1)
          head -n1 "$first" > inventory.csv

          # Append data rows from all chunk CSVs
          find . -type f -name 'inventory_*.csv' | while read f; do
            tail -n +2 "$f"
          done >> inventory.csv

          ls -lh inventory.csv

      - name: Upload final CSV
        uses: actions/upload-artifact@v4
        with:
          name: inventory.csv
          path: inventory.csv
