name: Scrape RKGuns Inventory

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -u -m pip install --upgrade pip
          python -u -m pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run scraper
        env:
          DISPLAY: ":99"
        run: python -u scraper_selenium.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory-csv
          path: inventory.csv
