# File: .github/workflows/scrape-debug.yml
name: Debug RK Guns Scraper

on:
  workflow_dispatch:

jobs:
  debug-scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install debug dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4

      - name: Run debug scraper
        run: python debug_scrape.py
