# File: .github/workflows/scrape.yml
name: Scrape Firearms Inventory

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install magento-py-scraper from GitHub
        run: pip install --upgrade pip && \
             pip install git+https://github.com/hectorherranz/magento-py-scraper.git

      - name: Install other dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory-csv
          path: inventory.csv
