name: Scrape Firearms Inventory

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python & ChromeDriver
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Install Chrome and driver:
      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
          wget -qO /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i /tmp/chrome.deb || sudo apt-get -f install -y
          LATEST=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -qO /tmp/chromedriver.zip \
            https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip
          sudo unzip -o /tmp/chromedriver.zip -d /usr/local/bin

      - name: Run scraper
        run: python scraper_selenium.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory-csv
          path: inventory.csv
